{"name": "test_login_incorrect_phone", "status": "failed", "statusDetails": {"message": "AssertionError: assert 200 == 201\n +  where 200 = <Response [200]>.status_code", "trace": "self = <API_test_QA.Tests.test_QA_logInAPI.Test_Trado_Admin_Login object at 0x0000023D5CE15000>\n\n    @allure.description('Login correctly using Invalid Phone number')\n    @pytest.mark.sanity\n    def test_login_incorrect_phone(self):\n        url = Login_locaters_QA_api.URL_LOGIN\n        data = Login_locaters_QA_api.INVALID_PHONE\n        Req = requests.post(url, json=data)\n>       assert Req.status_code == 201\nE       assert 200 == 201\nE        +  where 200 = <Response [200]>.status_code\n\ntest_QA_logInAPI.py:23: AssertionError"}, "description": "Login correctly using Invalid Phone number", "start": 1677098819667, "stop": 1677098820014, "uuid": "0d508497-02d1-4cf2-a2b2-b3b381f3f400", "historyId": "3b29bc1cf11c70eb3f6ce5cfbee7d5ce", "testCaseId": "2f6d744e338c7ee84bc741e13e4d3a3d", "fullName": "test_QA_logInAPI.Test_Trado_Admin_Login#test_login_incorrect_phone", "labels": [{"name": "tag", "value": "sanity"}, {"name": "suite", "value": "test_QA_logInAPI"}, {"name": "subSuite", "value": "Test_Trado_Admin_Login"}, {"name": "host", "value": "LAPTOP-58MDPDG0"}, {"name": "thread", "value": "13144-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_QA_logInAPI"}]}