{"name": "test_SignUp_with_incorrectly_phone", "status": "failed", "statusDetails": {"message": "AssertionError: assert 200 == 300\n +  where 200 = <Response [200]>.status_code", "trace": "self = <API_test_QA.Tests.test_QA_SignUpAPI.Test_Login object at 0x0000023D5CE144C0>\n\n    @allure.description('SignUp when UserName incorrectly')\n    def test_SignUp_with_incorrectly_phone(self):\n        url = SignUp_Locators.URL_SIGN_UP\n        data = SignUp_Locators.INCORRECT_PHONE\n        Req = requests.post(url, json=data)\n>       assert Req.status_code == 300\nE       assert 200 == 300\nE        +  where 200 = <Response [200]>.status_code\n\ntest_QA_SignUpAPI.py:30: AssertionError"}, "description": "SignUp when UserName incorrectly", "start": 1677098813944, "stop": 1677098814274, "uuid": "0ef942c4-dbdf-4dd4-a57a-318d399fbbe8", "historyId": "99d4d80d8a0ce52253c36fdd490cc306", "testCaseId": "feb822c83ec338f42097844b02ae22d3", "fullName": "test_QA_SignUpAPI.Test_Login#test_SignUp_with_incorrectly_phone", "labels": [{"name": "suite", "value": "test_QA_SignUpAPI"}, {"name": "subSuite", "value": "Test_Login"}, {"name": "host", "value": "LAPTOP-58MDPDG0"}, {"name": "thread", "value": "13144-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_QA_SignUpAPI"}]}