{"name": "test_JoinUs_using_Letter_BnNumber_", "status": "failed", "statusDetails": {"message": "AssertionError", "trace": "self = <TRADO.QA_WEB.Utils.utils_QA.Utils object at 0x00000131521A1870>, expected = 'abcd', actual = ''\n\n    @allure.step\n    @allure.description('This validation method, if the assert failed it will take screenshot')\n    def assertion(self, expected, actual):\n        driver = self.driver\n        try:\n>           assert expected == actual\nE           AssertionError\n\n..\\Utils\\utils_QA.py:15: AssertionError\n\nDuring handling of the above exception, another exception occurred:\n\nself = <TRADO.QA_WEB.Tests.testQA_Business_interface.TestQA_Business_Interface_Chrome2 object at 0x00000131518EFB20>\n\n    @pytest.mark.sanity\n    @allure.description('Successfully Join using letter BnNumber input')\n    @allure.severity(allure.severity_level.NORMAL)\n    def test_JoinUs_using_Letter_BnNumber_(self):\n        driver = self.driver\n        join = Business_Interface_Page(driver)\n        join.Click_Business_Interface_Box()\n        join.Enter_FirstName_box('team')\n        join.Enter_LastName_Box('two')\n>       join.Enter_BnNumber_box('abcd')\n\ntestQA_Business_interface.py:453: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n..\\Pages\\businessInterfaceQA_page.py:52: in Enter_BnNumber_box\n    Utils(self.driver).assertion(BnNumber, BnNumber_input.get_attribute('value'))\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <TRADO.QA_WEB.Utils.utils_QA.Utils object at 0x00000131521A1870>, expected = 'abcd', actual = ''\n\n    @allure.step\n    @allure.description('This validation method, if the assert failed it will take screenshot')\n    def assertion(self, expected, actual):\n        driver = self.driver\n        try:\n            assert expected == actual\n            self.driver.implicitly_wait(1000)\n    \n        except AssertionError:\n            allure.attach(driver.get_screenshot_as_png(), name='screenShot',attachment_type=AttachmentType.PNG)\n>           raise AssertionError\nE           AssertionError\n\n..\\Utils\\utils_QA.py:20: AssertionError"}, "description": "Successfully Join using letter BnNumber input", "steps": [{"name": "Click_Business_Interface_Box", "status": "passed", "start": 1677091631298, "stop": 1677091632383}, {"name": "Enter_FirstName_box", "status": "passed", "steps": [{"name": "assertion", "status": "passed", "parameters": [{"name": "expected", "value": "'team'"}, {"name": "actual", "value": "'team'"}], "start": 1677091632463, "stop": 1677091632465}], "parameters": [{"name": "First_Name", "value": "'team'"}], "start": 1677091632383, "stop": 1677091632467}, {"name": "Enter_LastName_Box", "status": "passed", "steps": [{"name": "assertion", "status": "passed", "parameters": [{"name": "expected", "value": "'two'"}, {"name": "actual", "value": "'two'"}], "start": 1677091632551, "stop": 1677091632552}], "parameters": [{"name": "Last_Name", "value": "'two'"}], "start": 1677091632467, "stop": 1677091632554}, {"name": "Enter_BnNumber_box", "status": "failed", "statusDetails": {"message": "AssertionError\n", "trace": "  File \"C:\\Users\\user\\QA_Automation\\2023_Final_Project\\venv\\lib\\site-packages\\allure_commons\\_allure.py\", line 192, in impl\n    return func(*a, **kw)\n  File \"C:\\Users\\user\\QA_Automation\\2023_Final_Project\\TRADO\\QA_WEB\\Pages\\businessInterfaceQA_page.py\", line 52, in Enter_BnNumber_box\n    Utils(self.driver).assertion(BnNumber, BnNumber_input.get_attribute('value'))\n  File \"C:\\Users\\user\\QA_Automation\\2023_Final_Project\\venv\\lib\\site-packages\\allure_commons\\_allure.py\", line 192, in impl\n    return func(*a, **kw)\n  File \"C:\\Users\\user\\QA_Automation\\2023_Final_Project\\TRADO\\QA_WEB\\Utils\\utils_QA.py\", line 20, in assertion\n    raise AssertionError\n"}, "steps": [{"name": "assertion", "status": "failed", "statusDetails": {"message": "AssertionError\n", "trace": "  File \"C:\\Users\\user\\QA_Automation\\2023_Final_Project\\venv\\lib\\site-packages\\allure_commons\\_allure.py\", line 192, in impl\n    return func(*a, **kw)\n  File \"C:\\Users\\user\\QA_Automation\\2023_Final_Project\\TRADO\\QA_WEB\\Utils\\utils_QA.py\", line 20, in assertion\n    raise AssertionError\n"}, "attachments": [{"name": "screenShot", "source": "bb22c838-13cb-4a63-80d9-2a7c450d0de1-attachment.png", "type": "image/png"}], "parameters": [{"name": "expected", "value": "'abcd'"}, {"name": "actual", "value": "''"}], "start": 1677091632611, "stop": 1677091632768}], "parameters": [{"name": "BnNumber", "value": "'abcd'"}], "start": 1677091632554, "stop": 1677091632769}], "attachments": [{"name": "stdout", "source": "63ebe26e-85a6-40c7-bf0d-ca622ef1b89d-attachment.txt", "type": "text/plain"}], "start": 1677091631298, "stop": 1677091632770, "uuid": "994ee997-6824-474c-9f20-90f262a1056a", "historyId": "3035b8a3b315592f0e967713acca56e6", "testCaseId": "e3bdf104ea1da270808c279d0876940a", "fullName": "testQA_Business_interface.TestQA_Business_Interface_Chrome2#test_JoinUs_using_Letter_BnNumber_", "labels": [{"name": "severity", "value": "normal"}, {"name": "tag", "value": "sanity"}, {"name": "tag", "value": "@pytest.mark.usefixtures('WithOut_login_selectField_restaurant_and_cocktails')"}, {"name": "suite", "value": "testQA_Business_interface"}, {"name": "subSuite", "value": "TestQA_Business_Interface_Chrome2"}, {"name": "host", "value": "LAPTOP-42FB6NAB"}, {"name": "thread", "value": "20332-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testQA_Business_interface"}]}